use anyhow::{anyhow, Result};
use std::collections::HashMap;
use std::fs::File;
use std::io::{BufReader, Read, Seek, SeekFrom, Write};
use std::ops::{Bound, Deref, Range, RangeBounds};
use std::path::Path;
use wide::u8x16;

/// SIMD implementation selector for [`Blocks::from_dna`], mainly for
/// benchmarking and diagnostics (same policy as `libs::nt_simd`).
#[derive(Clone, Copy, Debug)]
pub enum SimdPath {
    /// Runtime detection: AVX2 on capable x86-64, 128-bit wide elsewhere.
    Auto,
    /// Force the 128-bit `wide` path (SSE2 / NEON).
    Wide,
    /// Force the AVX2 path (falls back to `wide` without AVX2).
    Avx2,
    /// Force the pure scalar fallback.
    Scalar,
}

const TWOBIT_MAGIC: u32 = 0x1A412743;
const TWOBIT_MAGIC_SWAPPED: u32 = 0x4327411A;

/// A 0-based half-open interval representing a masked region within a sequence.
pub type Block = Range<usize>;

/// A collection of masked regions (N-blocks or soft-mask blocks) for a sequence.
#[derive(Debug, Clone)]
pub struct Blocks(pub Vec<Block>);

impl Deref for Blocks {
    type Target = [Block];

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl Blocks {
    /// Return an iterator over blocks overlapping the given half-open range.
    pub fn overlaps(&self, range: impl RangeBounds<usize>) -> impl Iterator<Item = &Block> {
        let start = match range.start_bound() {
            Bound::Included(&x) => x,
            Bound::Excluded(&x) => x + 1,
            Bound::Unbounded => 0,
        };
        let end = match range.end_bound() {
            Bound::Included(&x) => x + 1,
            Bound::Excluded(&x) => x,
            Bound::Unbounded => usize::MAX,
        };

        self.0
            .iter()
            // Assume blocks are sorted
            .skip_while(move |block| block.end <= start)
            .take_while(move |block| block.start < end)
    }

    /// Replace overlapping positions in `seq` with 'N', using 0-based global coordinates.
    pub fn apply_hard_mask(&self, seq: &mut [u8], offset: usize) {
        let (start, end) = (offset, offset + seq.len());
        for block in self.overlaps(start..end) {
            let seq_start = start.max(block.start) - start;
            let seq_end = end.min(block.end) - start;
            seq[seq_start..seq_end].fill(b'N');
        }
    }

    /// Convert overlapping positions in `seq` to lowercase, using 0-based global coordinates.
    pub fn apply_soft_mask(&self, seq: &mut [u8], offset: usize) {
        let (start, end) = (offset, offset + seq.len());
        for block in self.overlaps(start..end) {
            let seq_start = start.max(block.start) - start;
            let seq_end = end.min(block.end) - start;
            for byte in &mut seq[seq_start..seq_end] {
                *byte = byte.to_ascii_lowercase();
            }
        }
    }

    /// Pack a DNA string into 2-bit data, returning `(packed, n_blocks, mask_blocks, dna_size)`.
    ///
    /// Bases that are not A/C/G/T (case-insensitive), including IUPAC ambiguity
    /// codes and U, are treated as N and recorded as hard-mask blocks. Lowercase
    /// A/C/G/T bases are recorded as soft-mask blocks when `do_mask` is true.
    ///
    /// Returns an error if the sequence length exceeds the 2bit u32 size limit.
    pub fn from_dna(dna: &str, do_mask: bool) -> Result<(Vec<u8>, Blocks, Blocks, u32)> {
        let len = dna.len();
        let dna_size = u32_dna_size(len)?;
        let classes = classify_dna_with(SimdPath::Auto, dna.as_bytes());
        let n_blocks = blocks_from_mask(&classes.n_mask, len);
        let mask_blocks = if do_mask {
            blocks_from_mask(&classes.lower_mask, len)
        } else {
            Vec::new()
        };
        let packed_dna = pack_codes(&classes.codes);
        Ok((packed_dna, Blocks(n_blocks), Blocks(mask_blocks), dna_size))
    }
}

/// Per-base classifier output for [`Blocks::from_dna`]: N/lowercase bitmasks
/// (one `u32` per 32 bases) plus the 2-bit code per base (T=0, C=1, A=2,
/// G=3, N/IUPAC/U=0). Generated by AVX2 / 128-bit wide / scalar paths.
pub struct DnaClasses {
    pub n_mask: Vec<u32>,
    pub lower_mask: Vec<u32>,
    pub codes: Vec<u8>,
}

/// [`Blocks::from_dna`] classifier with an explicit implementation path.
pub fn classify_dna_with(path: SimdPath, dna: &[u8]) -> DnaClasses {
    let n_words = dna.len().div_ceil(32);
    let mut out = DnaClasses {
        n_mask: vec![0; n_words],
        lower_mask: vec![0; n_words],
        codes: vec![0; dna.len()],
    };
    match path {
        SimdPath::Scalar => classify_scalar(dna, &mut out),
        SimdPath::Wide => classify_wide(dna, &mut out),
        SimdPath::Auto | SimdPath::Avx2 => {
            #[cfg(target_arch = "x86_64")]
            if is_x86_feature_detected!("avx2") {
                // SAFETY: gated on runtime AVX2 support.
                unsafe { avx2::classify_avx2(dna, &mut out) };
                return out;
            }
            classify_wide(dna, &mut out);
        }
    }
    out
}

/// Scalar reference classification, kept as the test contract (the product
/// paths are AVX2 -> 128-bit wide; scalar is the fallback for SIMD-less
/// targets if wide ever fails to compile there).
fn classify_scalar(dna: &[u8], out: &mut DnaClasses) {
    for (i, &b) in dna.iter().enumerate() {
        let l = b | 0x20;
        let is_n = !matches!(l, b'a' | b'c' | b'g' | b't');
        if is_n {
            out.n_mask[i / 32] |= 1 << (i % 32);
        }
        if b.is_ascii_lowercase() {
            out.lower_mask[i / 32] |= 1 << (i % 32);
        }
        out.codes[i] = match l {
            b't' => 0,
            b'c' => 1,
            b'a' => 2,
            b'g' => 3,
            _ => 0,
        };
    }
}

/// 128-bit `wide` path (SSE2 on x86-64 / NEON on aarch64; independent of
/// the compile-time avx2 flag).
fn classify_wide(dna: &[u8], out: &mut DnaClasses) {
    let or20 = u8x16::splat(0x20);
    let (chunks, rem) = dna.as_chunks::<32>();
    for (wi, chunk) in chunks.iter().enumerate() {
        let lo: [u8; 16] = chunk[..16].try_into().unwrap();
        let hi: [u8; 16] = chunk[16..].try_into().unwrap();
        let (n_lo, lower_lo, code_lo) = classify_16(u8x16::from(lo), or20);
        let (n_hi, lower_hi, code_hi) = classify_16(u8x16::from(hi), or20);
        out.n_mask[wi] = (n_lo as u32) | ((n_hi as u32) << 16);
        out.lower_mask[wi] = (lower_lo as u32) | ((lower_hi as u32) << 16);
        out.codes[wi * 32..wi * 32 + 16].copy_from_slice(&code_lo);
        out.codes[wi * 32 + 16..wi * 32 + 32].copy_from_slice(&code_hi);
    }
    let base = chunks.len() * 32;
    if !rem.is_empty() {
        let mut n = out.n_mask[chunks.len()];
        let mut lower = out.lower_mask[chunks.len()];
        for (k, (&b, c)) in rem.iter().zip(out.codes[base..].iter_mut()).enumerate() {
            let l = b | 0x20;
            if !matches!(l, b'a' | b'c' | b'g' | b't') {
                n |= 1 << k;
            }
            if b.is_ascii_lowercase() {
                lower |= 1 << k;
            }
            *c = match l {
                b't' => 0,
                b'c' => 1,
                b'a' => 2,
                b'g' => 3,
                _ => 0,
            };
        }
        out.n_mask[chunks.len()] = n;
        out.lower_mask[chunks.len()] = lower;
    }
}

/// One 16-lane chunk: N/lower 16-bit masks plus 2-bit codes.
fn classify_16(v: u8x16, or20: u8x16) -> (u16, u16, [u8; 16]) {
    let l = v | or20;
    let eq_a = eq_bits16(l, u8x16::splat(b'a'));
    let eq_c = eq_bits16(l, u8x16::splat(b'c'));
    let eq_g = eq_bits16(l, u8x16::splat(b'g'));
    let eq_t = eq_bits16(l, u8x16::splat(b't'));
    let n_mask = !(eq_a | eq_c | eq_g | eq_t);
    let ge_a = eq_bits16(v.max(u8x16::splat(0x61)), v);
    let le_z = eq_bits16(v.min(u8x16::splat(0x7A)), v);
    let lower_mask = ge_a & le_z;
    let code_vec = (l.simd_eq(u8x16::splat(b'c')) & u8x16::splat(1))
        | (l.simd_eq(u8x16::splat(b'a')) & u8x16::splat(2))
        | (l.simd_eq(u8x16::splat(b'g')) & u8x16::splat(3));
    (n_mask, lower_mask, code_vec.to_array())
}

/// Lane-wise `a == x` as a 16-bit mask (bit set per matching lane).
#[inline]
fn eq_bits16(a: u8x16, x: u8x16) -> u16 {
    let d = a.saturating_sub(x) | x.saturating_sub(a);
    let ne = d | (!d + u8x16::splat(1));
    !ne.to_bitmask() as u16
}

#[cfg(target_arch = "x86_64")]
mod avx2 {
    use super::*;
    use std::arch::x86_64::*;

    #[inline]
    unsafe fn load(ptr: *const u8) -> __m256i {
        _mm256_loadu_si256(ptr as *const __m256i)
    }

    #[inline]
    unsafe fn set1(b: u8) -> __m256i {
        _mm256_set1_epi8(b as i8)
    }

    /// AVX2 classify: one 32-base chunk -> N/lower masks and 2-bit codes.
    #[target_feature(enable = "avx2")]
    pub(super) unsafe fn classify_avx2(dna: &[u8], out: &mut DnaClasses) {
        let (chunks, rem) = dna.as_chunks::<32>();
        for (wi, chunk) in chunks.iter().enumerate() {
            let v = load(chunk.as_ptr());
            let l = _mm256_or_si256(v, set1(0x20));
            let eq_a = _mm256_cmpeq_epi8(l, set1(b'a'));
            let eq_c = _mm256_cmpeq_epi8(l, set1(b'c'));
            let eq_g = _mm256_cmpeq_epi8(l, set1(b'g'));
            let eq_t = _mm256_cmpeq_epi8(l, set1(b't'));
            let any = _mm256_or_si256(_mm256_or_si256(eq_a, eq_c), _mm256_or_si256(eq_g, eq_t));
            out.n_mask[wi] = !_mm256_movemask_epi8(any) as u32;
            let ge_a = _mm256_cmpeq_epi8(_mm256_max_epu8(v, set1(0x61)), v);
            let le_z = _mm256_cmpeq_epi8(_mm256_min_epu8(v, set1(0x7A)), v);
            out.lower_mask[wi] = _mm256_movemask_epi8(_mm256_and_si256(ge_a, le_z)) as u32;
            let code = _mm256_or_si256(
                _mm256_and_si256(eq_c, set1(1)),
                _mm256_or_si256(
                    _mm256_and_si256(eq_a, set1(2)),
                    _mm256_and_si256(eq_g, set1(3)),
                ),
            );
            _mm256_storeu_si256(
                out.codes[wi * 32..wi * 32 + 32].as_mut_ptr() as *mut __m256i,
                code,
            );
        }
        let base = chunks.len() * 32;
        if !rem.is_empty() {
            let mut n = out.n_mask[chunks.len()];
            let mut lower = out.lower_mask[chunks.len()];
            for (k, (&b, c)) in rem.iter().zip(out.codes[base..].iter_mut()).enumerate() {
                let l = b | 0x20;
                if !matches!(l, b'a' | b'c' | b'g' | b't') {
                    n |= 1 << k;
                }
                if b.is_ascii_lowercase() {
                    lower |= 1 << k;
                }
                *c = match l {
                    b't' => 0,
                    b'c' => 1,
                    b'a' => 2,
                    b'g' => 3,
                    _ => 0,
                };
            }
            out.n_mask[chunks.len()] = n;
            out.lower_mask[chunks.len()] = lower;
        }
    }
}

/// Merges set bits of `mask` into `[start, end)` ranges, stopping at `len`.
fn blocks_from_mask(mask: &[u32], len: usize) -> Vec<Range<usize>> {
    let mut blocks = Vec::new();
    let mut begin: Option<usize> = None;
    let mut end: Option<usize> = None;
    for (wi, &w) in mask.iter().enumerate() {
        let base = wi * 32;
        let n_in_word = 32.min(len - base);
        let word_bits = if n_in_word == 32 {
            u32::MAX
        } else {
            (1u32 << n_in_word) - 1
        };
        let mut rem = w & word_bits;
        let mut col = 0usize;
        while rem != 0 {
            let tz = rem.trailing_zeros() as usize;
            let ones = (rem >> tz).trailing_ones() as usize;
            let s = base + col + tz;
            let e = s + ones; // half-open end, matching `Range` blocks
            match end {
                Some(prev_end) if s == prev_end => end = Some(e),
                Some(prev_end) => {
                    blocks.push(begin.unwrap()..prev_end);
                    begin = Some(s);
                    end = Some(e);
                }
                None => {
                    begin = Some(s);
                    end = Some(e);
                }
            }
            col = col + tz + ones;
            rem = if tz + ones >= 32 {
                0
            } else {
                rem >> (tz + ones)
            };
        }
    }
    if let (Some(b), Some(e)) = (begin, end) {
        blocks.push(b..e);
    }
    blocks
}

/// Packs 2-bit codes into bytes, 4 codes per byte, high bits first.
fn pack_codes(codes: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(codes.len().div_ceil(4));
    for chunk in codes.chunks(4) {
        let mut byte = 0u8;
        for (k, &c) in chunk.iter().enumerate() {
            byte |= c << (6 - 2 * k);
        }
        out.push(byte);
    }
    out
}

/// Validate that a DNA length fits in the 2bit u32 size field.
fn u32_dna_size(len: usize) -> Result<u32> {
    u32::try_from(len).map_err(|_| {
        anyhow!(
            "sequence length {} exceeds 2bit u32 limit ({})",
            len,
            u32::MAX
        )
    })
}

/// Read and decode a single 2bit record, optionally sub-sampled, with masks applied.
pub fn read_2bit_record<R: Read + Seek>(
    reader: &mut R,
    is_swapped: bool,
    start: Option<usize>,
    end: Option<usize>,
    no_mask: bool,
) -> Result<String> {
    // The reader must be positioned at the start of the record (dna_size field).
    let dna_size = read_u32(reader, is_swapped)? as usize;

    let n_blocks = read_blocks(reader, is_swapped)?;
    let mask_blocks = read_blocks(reader, is_swapped)?;

    let _reserved = read_u32(reader, is_swapped)?;

    let start_pos = start.unwrap_or(0);
    let end_pos = end.unwrap_or(dna_size).min(dna_size);

    if start_pos > dna_size {
        return Err(anyhow!(
            "start {} exceeds sequence length {}",
            start_pos,
            dna_size
        ));
    }

    if start_pos >= end_pos {
        return Ok(String::new());
    }

    // Currently at the start of packed DNA.
    let packed_dna_start = reader.stream_position()?;

    let first_byte_idx = start_pos / 4;
    let last_byte_idx = (end_pos - 1) / 4;

    reader.seek(SeekFrom::Start(packed_dna_start + first_byte_idx as u64))?;

    let mut packed_buf = vec![0u8; last_byte_idx - first_byte_idx + 1];
    reader.read_exact(&mut packed_buf)?;

    let table = *b"TCAG";

    let mut seq_vec = Vec::with_capacity(end_pos - start_pos);
    for i in start_pos..end_pos {
        let global_byte_idx = i / 4;
        let local_byte_idx = global_byte_idx - first_byte_idx;
        let bit_offset = 6 - 2 * (i % 4); // 0->6, 1->4, 2->2, 3->0

        let byte = packed_buf[local_byte_idx];
        let val = (byte >> bit_offset) & 3;
        seq_vec.push(table[val as usize]);
    }

    n_blocks.apply_hard_mask(&mut seq_vec, start_pos);

    if !no_mask {
        mask_blocks.apply_soft_mask(&mut seq_vec, start_pos);
    }

    String::from_utf8(seq_vec).map_err(|e| anyhow!("invalid UTF-8 in 2bit sequence: {}", e))
}

/// Write a single 2bit record from already packed DNA and block metadata.
pub fn write_packed_record<W: Write>(
    writer: &mut W,
    dna_size: u32,
    n_blocks: &Blocks,
    mask_blocks: &Blocks,
    packed: &[u8],
) -> Result<()> {
    writer.write_all(&dna_size.to_le_bytes())?;

    writer.write_all(&(n_blocks.0.len() as u32).to_le_bytes())?;
    for block in &n_blocks.0 {
        writer.write_all(&(block.start as u32).to_le_bytes())?;
    }
    for block in &n_blocks.0 {
        writer.write_all(&((block.end - block.start) as u32).to_le_bytes())?;
    }

    writer.write_all(&(mask_blocks.0.len() as u32).to_le_bytes())?;
    for block in &mask_blocks.0 {
        writer.write_all(&(block.start as u32).to_le_bytes())?;
    }
    for block in &mask_blocks.0 {
        writer.write_all(&((block.end - block.start) as u32).to_le_bytes())?;
    }

    writer.write_all(&0u32.to_le_bytes())?;
    writer.write_all(packed)?;

    Ok(())
}

/// Write a single 2bit record to the writer, including blocks and packed DNA.
pub fn write_2bit_record<W: Write>(writer: &mut W, dna: &str, do_mask: bool) -> Result<()> {
    let (packed, n_blocks, mask_blocks, dna_size) = Blocks::from_dna(dna, do_mask)?;
    write_packed_record(writer, dna_size, &n_blocks, &mask_blocks, &packed)
}

/// Read a block list (count + starts + sizes) from a 2bit record.
pub fn read_blocks<R: Read>(reader: &mut R, is_swapped: bool) -> Result<Blocks> {
    let count = read_u32(reader, is_swapped)? as usize;
    let starts = read_u32_vec(reader, count, is_swapped)?;
    let sizes = read_u32_vec(reader, count, is_swapped)?;

    let blocks: Vec<Block> = starts
        .into_iter()
        .zip(sizes)
        .map(|(start, size)| {
            let s = start as usize;
            let e = s + size as usize;
            s..e
        })
        .collect();

    Ok(Blocks(blocks))
}

/// Read a complete 2bit record (positioned at its dna_size field) and return
/// its N-blocks, soft-mask blocks, and unmasked sequence.
fn load_full_record<R: Read + Seek>(
    reader: &mut R,
    is_swapped: bool,
) -> Result<(Blocks, Blocks, String)> {
    let dna_size = read_u32(reader, is_swapped)? as usize;

    let n_blocks = read_blocks(reader, is_swapped)?;
    let mask_blocks = read_blocks(reader, is_swapped)?;

    let _reserved = read_u32(reader, is_swapped)?;

    let mut packed_buf = vec![0u8; dna_size.div_ceil(4)];
    reader.read_exact(&mut packed_buf)?;

    let table = *b"TCAG";

    let mut seq_vec = Vec::with_capacity(dna_size);
    for i in 0..dna_size {
        let byte = packed_buf[i / 4];
        let bit_offset = 6 - 2 * (i % 4); // 0->6, 1->4, 2->2, 3->0
        seq_vec.push(table[((byte >> bit_offset) & 3) as usize]);
    }

    let seq =
        String::from_utf8(seq_vec).map_err(|e| anyhow!("invalid UTF-8 in 2bit sequence: {}", e))?;

    Ok((n_blocks, mask_blocks, seq))
}

/// A writer for the 2bit binary sequence format.
pub struct TwoBitWriter<W> {
    writer: W,
}

impl<W: std::io::Write> TwoBitWriter<W> {
    /// Create a new 2bit writer wrapping the given output.
    pub fn new(writer: W) -> Self {
        Self { writer }
    }

    /// Write a complete 2bit file with the given sequences and optional soft-masking.
    pub fn write(&mut self, sequences: &[(&str, &str)], do_mask: bool) -> Result<()> {
        // Pack each sequence once and reuse the result for sizing and writing.
        let mut packed_records = Vec::with_capacity(sequences.len());
        for (_, dna) in sequences {
            let (packed, n_blocks, mask_blocks, dna_size) = Blocks::from_dna(dna, do_mask)?;
            packed_records.push((packed, n_blocks, mask_blocks, dna_size));
        }

        // 1. Write Header
        self.writer.write_all(&TWOBIT_MAGIC.to_le_bytes())?;
        self.writer.write_all(&1u32.to_le_bytes())?; // Version 1
        self.writer
            .write_all(&(sequences.len() as u32).to_le_bytes())?; // SeqCount
        self.writer.write_all(&0u32.to_le_bytes())?; // Reserved

        // 2. Calculate offsets and Write Index
        // Header is 16 bytes; index starts at byte 16.
        // Index entry: NameLen(1) + Name(N) + Offset(8)
        let mut current_offset = 16u64;
        for (name, _) in sequences {
            current_offset += 1 + name.len() as u64 + 8;
        }
        let mut running_offset = current_offset;

        for ((name, _), (packed, n_blocks, mask_blocks, _)) in sequences.iter().zip(&packed_records)
        {
            if name.len() > 255 {
                return Err(anyhow!("Sequence name too long: {}", name));
            }
            self.writer.write_all(&[name.len() as u8])?;
            self.writer.write_all(name.as_bytes())?;
            self.writer.write_all(&running_offset.to_le_bytes())?;

            let n_count = n_blocks.0.len() as u64;
            let mask_count = mask_blocks.0.len() as u64;
            let packed_len = packed.len() as u64;

            let record_size = 4 + // dnaSize
                4 + (n_count * 4) + (n_count * 4) + // N blocks
                4 + (mask_count * 4) + (mask_count * 4) + // Mask blocks
                4 + // reserved
                packed_len;

            running_offset += record_size;
        }

        // 3. Write Records
        for (packed, n_blocks, mask_blocks, dna_size) in &packed_records {
            write_packed_record(&mut self.writer, *dna_size, n_blocks, mask_blocks, packed)?;
        }

        Ok(())
    }
}

/// A random-access reader for the 2bit binary sequence format.
#[derive(Debug)]
pub struct TwoBitFile<R> {
    reader: R,
    /// Map of sequence name to the file offset of its record.
    pub sequence_offsets: HashMap<String, u64>,
    /// Sequence names in the order they appear in the file.
    pub sequence_order: Vec<String>,
    is_swapped: bool,
    /// 2bit file format version (0 or 1).
    pub version: u32,
    /// Cache of the most recently loaded full sequence (unmasked) plus its
    /// N/mask blocks, so repeated reads on the same chromosome avoid
    /// per-call seek+read syscalls (mirrors UCSC loadIfNewSeq).
    cached: Option<CachedRecord>,
}

#[derive(Debug)]
struct CachedRecord {
    name: String,
    n_blocks: Blocks,
    mask_blocks: Blocks,
    seq: String,
}

impl TwoBitFile<BufReader<File>> {
    /// Open a 2bit file from a path using a buffered file reader.
    pub fn open<P: AsRef<Path>>(path: P) -> Result<Self> {
        let file = File::open(path)?;
        let reader = BufReader::new(file);
        Self::new(reader)
    }
}

impl TwoBitFile<std::io::Cursor<Vec<u8>>> {
    /// Read an entire 2bit file into memory and open it from a cursor.
    pub fn open_and_read<P: AsRef<Path>>(path: P) -> Result<Self> {
        let mut buf = vec![];
        File::open(path)?.read_to_end(&mut buf)?;
        Self::new(std::io::Cursor::new(buf))
    }
}

impl<R: Read + Seek> TwoBitFile<R> {
    /// Parse a 2bit header and index from the given reader.
    pub fn new(mut reader: R) -> Result<Self> {
        // Read magic
        let mut buf = [0u8; 4];
        reader.read_exact(&mut buf)?;
        let magic = u32::from_le_bytes(buf);

        let is_swapped = if magic == TWOBIT_MAGIC {
            false
        } else if magic == TWOBIT_MAGIC_SWAPPED {
            true
        } else {
            return Err(anyhow!("Not a valid 2bit file (magic: {:x})", magic));
        };

        // Read version
        let version = read_u32(&mut reader, is_swapped)?;
        if version != 0 && version != 1 {
            return Err(anyhow!(
                "Unsupported 2bit version: {} (only version 0 and 1 are supported)",
                version
            ));
        }

        // Read seqCount
        let seq_count = read_u32(&mut reader, is_swapped)?;

        // Read reserved
        let _reserved = read_u32(&mut reader, is_swapped)?;

        // Read Index
        let mut sequence_offsets = HashMap::new();
        let mut sequence_order = Vec::new();
        for _ in 0..seq_count {
            let mut len_buf = [0u8; 1];
            reader.read_exact(&mut len_buf)?;
            let name_len = len_buf[0] as usize;

            let mut name_buf = vec![0u8; name_len];
            reader.read_exact(&mut name_buf)?;
            let name = String::from_utf8(name_buf)?;

            let offset = if version == 0 {
                read_u32(&mut reader, is_swapped)? as u64
            } else {
                read_u64(&mut reader, is_swapped)?
            };
            sequence_offsets.insert(name.clone(), offset);
            sequence_order.push(name);
        }

        Ok(Self {
            reader,
            sequence_offsets,
            sequence_order,
            is_swapped,
            version,
            cached: None,
        })
    }

    /// Return the sequence names in their original file order.
    pub fn get_sequence_names(&self) -> Vec<String> {
        self.sequence_order.clone()
    }

    /// Return true if the named sequence exists in the file.
    pub fn has_sequence(&self, name: &str) -> bool {
        self.sequence_offsets.contains_key(name)
    }

    fn read_blocks(&mut self) -> Result<Blocks> {
        read_blocks(&mut self.reader, self.is_swapped)
    }

    /// Read a sequence by name; `start`/`end` are 0-based half-open (None = full) and masks are applied unless `no_mask` is true.
    pub fn read_sequence(
        &mut self,
        name: &str,
        start: Option<usize>,
        end: Option<usize>,
        no_mask: bool,
    ) -> Result<String> {
        let offset = *self
            .sequence_offsets
            .get(name)
            .ok_or_else(|| anyhow!("Sequence not found: {}", name))?;

        if self.cached.as_ref().is_none_or(|c| c.name != name) {
            self.reader.seek(SeekFrom::Start(offset))?;
            let (n_blocks, mask_blocks, seq) = load_full_record(&mut self.reader, self.is_swapped)?;
            self.cached = Some(CachedRecord {
                name: name.to_string(),
                n_blocks,
                mask_blocks,
                seq,
            });
        }

        let cached = self.cached.as_ref().unwrap();
        let start_pos = start.unwrap_or(0);
        let end_pos = end.unwrap_or(cached.seq.len()).min(cached.seq.len());

        if start_pos > cached.seq.len() {
            return Err(anyhow!(
                "start {} exceeds sequence length {}",
                start_pos,
                cached.seq.len()
            ));
        }
        if start_pos >= end_pos {
            return Ok(String::new());
        }

        let mut seq_vec: Vec<u8> = cached.seq.as_bytes()[start_pos..end_pos].to_vec();
        cached.n_blocks.apply_hard_mask(&mut seq_vec, start_pos);
        if !no_mask {
            cached.mask_blocks.apply_soft_mask(&mut seq_vec, start_pos);
        }

        String::from_utf8(seq_vec).map_err(|e| anyhow!("invalid UTF-8 in 2bit sequence: {}", e))
    }

    /// Return the total length (including Ns) of the named sequence.
    pub fn get_sequence_len(&mut self, name: &str) -> Result<usize> {
        let offset = *self
            .sequence_offsets
            .get(name)
            .ok_or_else(|| anyhow!("Sequence not found: {}", name))?;

        self.reader.seek(SeekFrom::Start(offset))?;
        let dna_size = read_u32(&mut self.reader, self.is_swapped)? as usize;
        Ok(dna_size)
    }

    /// Return the N-blocks and soft-mask blocks for the named sequence.
    pub fn get_sequence_blocks(&mut self, name: &str) -> Result<(Blocks, Blocks)> {
        let offset = *self
            .sequence_offsets
            .get(name)
            .ok_or_else(|| anyhow!("Sequence not found: {}", name))?;

        self.reader.seek(SeekFrom::Start(offset))?;
        let _dna_size = read_u32(&mut self.reader, self.is_swapped)?;

        let n_blocks = self.read_blocks()?;
        let mask_blocks = self.read_blocks()?;

        Ok((n_blocks, mask_blocks))
    }

    /// Return the sequence length excluding N-blocks.
    pub fn get_sequence_len_no_ns(&mut self, name: &str) -> Result<usize> {
        let offset = *self
            .sequence_offsets
            .get(name)
            .ok_or_else(|| anyhow!("Sequence not found: {}", name))?;

        self.reader.seek(SeekFrom::Start(offset))?;
        let dna_size = read_u32(&mut self.reader, self.is_swapped)? as usize;

        let n_blocks = self.read_blocks()?;

        let n_count: usize = n_blocks.iter().map(|b| b.end - b.start).sum();

        if n_count > dna_size {
            return Err(anyhow!("N blocks size {} > dna size {}", n_count, dna_size));
        }

        Ok(dna_size - n_count)
    }
}

impl<R: Read + Seek> crate::libs::io::SequenceReader for TwoBitFile<R> {
    fn read_sequence(
        &mut self,
        name: &str,
        start: Option<usize>,
        end: Option<usize>,
    ) -> anyhow::Result<String> {
        // Delegate to the inherent 5-arg form, masking kept on (no_mask=false).
        TwoBitFile::read_sequence(self, name, start, end, false)
    }
}

/// Read a little-endian u32, byte-swapping if `is_swapped` is true.
pub fn read_u32<R: Read>(reader: &mut R, is_swapped: bool) -> Result<u32> {
    let mut buf = [0u8; 4];
    reader.read_exact(&mut buf)?;
    let val = u32::from_le_bytes(buf);
    if is_swapped {
        Ok(val.swap_bytes())
    } else {
        Ok(val)
    }
}

/// Read a little-endian u64, byte-swapping if `is_swapped` is true.
pub fn read_u64<R: Read>(reader: &mut R, is_swapped: bool) -> Result<u64> {
    let mut buf = [0u8; 8];
    reader.read_exact(&mut buf)?;
    let val = u64::from_le_bytes(buf);
    if is_swapped {
        Ok(val.swap_bytes())
    } else {
        Ok(val)
    }
}

/// Read `count` little-endian u32 values, byte-swapping if `is_swapped` is true.
pub fn read_u32_vec<R: Read>(reader: &mut R, count: usize, is_swapped: bool) -> Result<Vec<u32>> {
    let mut buf = vec![0u8; count * 4];
    reader.read_exact(&mut buf)?;
    let mut vec = Vec::with_capacity(count);
    for chunk in buf.chunks_exact(4) {
        let val = u32::from_le_bytes(chunk.try_into().unwrap());
        vec.push(if is_swapped { val.swap_bytes() } else { val });
    }
    Ok(vec)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::{rngs::StdRng, Rng, SeedableRng};
    use std::io::Cursor;

    fn random_dna(rng: &mut StdRng, len: usize) -> String {
        let alphabet = *b"ACGTacgtNMRWSYKVHDXnn-*_ 0123456789Uu";
        (0..len)
            .map(|_| alphabet[rng.random_range(0..alphabet.len())] as char)
            .collect()
    }

    #[test]
    fn classify_matches_scalar_random() {
        // AVX2 / wide paths must agree with the scalar reference on every
        // bit of the N/lower masks and every 2-bit code.
        let mut rng = StdRng::seed_from_u64(20260809);
        for len in [0usize, 1, 15, 16, 17, 31, 32, 33, 63, 64, 65, 500, 1000] {
            for _ in 0..10 {
                let dna = random_dna(&mut rng, len);
                for path in [SimdPath::Auto, SimdPath::Wide, SimdPath::Scalar] {
                    let got = classify_dna_with(path, dna.as_bytes());
                    let mut expected = DnaClasses {
                        n_mask: vec![0; got.n_mask.len()],
                        lower_mask: vec![0; got.lower_mask.len()],
                        codes: vec![0; len],
                    };
                    classify_scalar(dna.as_bytes(), &mut expected);
                    assert_eq!(
                        got.n_mask, expected.n_mask,
                        "n_mask len={len} path={path:?}"
                    );
                    assert_eq!(
                        got.lower_mask, expected.lower_mask,
                        "lower len={len} path={path:?}"
                    );
                    assert_eq!(got.codes, expected.codes, "codes len={len} path={path:?}");
                }
            }
        }
    }

    #[test]
    fn from_dna_matches_scalar_reference() {
        // Rebuild from_dna output from the scalar classifier and compare.
        let mut rng = StdRng::seed_from_u64(7);
        for len in [0usize, 1, 4, 5, 16, 17, 100] {
            for _ in 0..20 {
                let dna = random_dna(&mut rng, len);
                for do_mask in [false, true] {
                    let (packed, n_blocks, mask_blocks, size) =
                        Blocks::from_dna(&dna, do_mask).unwrap();
                    let mut classes = DnaClasses {
                        n_mask: vec![0; len.div_ceil(32)],
                        lower_mask: vec![0; len.div_ceil(32)],
                        codes: vec![0; len],
                    };
                    classify_scalar(dna.as_bytes(), &mut classes);
                    let n_ref = blocks_from_mask(&classes.n_mask, len);
                    let mask_ref = if do_mask {
                        blocks_from_mask(&classes.lower_mask, len)
                    } else {
                        Vec::new()
                    };
                    assert_eq!(packed, pack_codes(&classes.codes), "packed len={len}");
                    assert_eq!(n_blocks.0, n_ref, "n_blocks len={len}");
                    assert_eq!(mask_blocks.0, mask_ref, "mask_blocks len={len}");
                    assert_eq!(size, len as u32);
                }
            }
        }
    }

    fn create_v1_2bit_data() -> Vec<u8> {
        let mut data = Vec::new();

        // Header (16 bytes)
        data.extend_from_slice(&TWOBIT_MAGIC.to_le_bytes()); // Magic
        data.extend_from_slice(&1u32.to_le_bytes()); // Version 1
        data.extend_from_slice(&1u32.to_le_bytes()); // SeqCount 1
        data.extend_from_slice(&0u32.to_le_bytes()); // Reserved

        // Index
        // Name: "seq1"
        let name = "seq1";
        data.push(name.len() as u8);
        data.extend_from_slice(name.as_bytes());

        // Offset calculation:
        // Header (16) + NameLen(1) + Name(4) + Offset(8) = 29 bytes
        let offset = 29u64;
        data.extend_from_slice(&offset.to_le_bytes());

        // Data Record at offset 29
        // Sequence: TCAG (4 bp)
        // T=00, C=01, A=10, G=11 -> 00011011 = 0x1B
        let dna_size = 4u32;
        data.extend_from_slice(&dna_size.to_le_bytes());

        // N Blocks
        data.extend_from_slice(&0u32.to_le_bytes()); // Count

        // Mask Blocks
        data.extend_from_slice(&0u32.to_le_bytes()); // Count

        // Reserved
        data.extend_from_slice(&0u32.to_le_bytes());

        // Packed DNA
        data.push(0x1B); // TCAG

        data
    }

    #[test]
    fn test_read_v1_basic() -> Result<()> {
        let data = create_v1_2bit_data();
        let cursor = Cursor::new(data);
        let mut tb = TwoBitFile::new(cursor)?;

        assert_eq!(tb.version, 1);

        let names = tb.get_sequence_names();
        assert_eq!(names, vec!["seq1"]);

        // Read "seq1"
        let seq = tb.read_sequence("seq1", None, None, false)?;
        assert_eq!(seq, "TCAG");

        Ok(())
    }

    fn create_v0_2bit_data() -> Vec<u8> {
        let mut data = Vec::new();

        // Header (16 bytes)
        data.extend_from_slice(&TWOBIT_MAGIC.to_le_bytes()); // Magic
        data.extend_from_slice(&0u32.to_le_bytes()); // Version 0
        data.extend_from_slice(&1u32.to_le_bytes()); // SeqCount 1
        data.extend_from_slice(&0u32.to_le_bytes()); // Reserved

        // Index
        // Name: "seq1"
        let name = "seq1";
        data.push(name.len() as u8);
        data.extend_from_slice(name.as_bytes());

        // Offset calculation:
        // Header (16) + NameLen(1) + Name(4) + Offset(4) = 25 bytes
        let offset = 25u32;
        data.extend_from_slice(&offset.to_le_bytes());

        // Data Record at offset 25
        // Sequence: TCAG (4 bp)
        // T=00, C=01, A=10, G=11 -> 00011011 = 0x1B
        let dna_size = 4u32;
        data.extend_from_slice(&dna_size.to_le_bytes());

        // N Blocks
        data.extend_from_slice(&0u32.to_le_bytes()); // Count

        // Mask Blocks
        data.extend_from_slice(&0u32.to_le_bytes()); // Count

        // Reserved
        data.extend_from_slice(&0u32.to_le_bytes());

        // Packed DNA
        data.push(0x1B); // TCAG

        data
    }

    #[test]
    fn test_read_v0_basic() -> Result<()> {
        let data = create_v0_2bit_data();
        let cursor = Cursor::new(data);
        let mut tb = TwoBitFile::new(cursor)?;

        assert_eq!(tb.version, 0);

        let names = tb.get_sequence_names();
        assert_eq!(names, vec!["seq1"]);

        // Read "seq1"
        let seq = tb.read_sequence("seq1", None, None, false)?;
        assert_eq!(seq, "TCAG");

        Ok(())
    }

    #[test]
    fn test_version_check() {
        // Construct a version 2 file (unsupported)
        let mut data = Vec::new();
        data.extend_from_slice(&TWOBIT_MAGIC.to_le_bytes());
        data.extend_from_slice(&2u32.to_le_bytes()); // Version 2
                                                     // ... rest doesn't matter as it fails fast

        let cursor = Cursor::new(data);
        let res = TwoBitFile::new(cursor);
        assert!(res.is_err());
        assert!(res
            .unwrap_err()
            .to_string()
            .contains("Unsupported 2bit version: 2"));
    }

    #[test]
    fn test_blocks_from_dna() {
        let dna = "acGTNn";
        // a=2(10), c=1(01), G=3(11), T=0(00), N=0(00), n=0(00)
        // 10 01 11 00 -> 0x9C
        // 00 00 -> 0x00

        let (packed, n_blocks, mask_blocks, size) = Blocks::from_dna(dna, true).unwrap();
        assert_eq!(size, 6);
        assert_eq!(packed, vec![0x9C, 0x00]);

        // N blocks: 4..6 (N, n)
        assert_eq!(n_blocks.0, vec![4..6]);

        // Mask blocks: 0..2 (a, c), 5..6 (n)
        assert_eq!(mask_blocks.0, vec![0..2, 5..6]);
    }

    #[test]
    fn test_write_read_roundtrip() -> Result<()> {
        let seqs = vec![("seq1", "TCAG"), ("seq2", "aaNgg")];

        let mut buffer = Cursor::new(Vec::new());
        let mut writer = TwoBitWriter::new(&mut buffer);
        writer.write(&seqs, true)?;

        buffer.set_position(0);
        let mut reader = TwoBitFile::new(buffer)?;

        let mut names = reader.get_sequence_names();
        names.sort();
        assert_eq!(names, vec!["seq1", "seq2"]);

        let s1 = reader.read_sequence("seq1", None, None, false)?;
        assert_eq!(s1, "TCAG");

        let s2 = reader.read_sequence("seq2", None, None, false)?;
        assert_eq!(s2, "aaNgg");

        Ok(())
    }

    // --- Independent tests for shared read_2bit_record / write_2bit_record ---

    #[test]
    fn test_record_roundtrip_acgt() -> Result<()> {
        let dna = "TCAGTCAG";
        let mut buf = Vec::new();
        write_2bit_record(&mut buf, dna, false)?;

        let mut cursor = Cursor::new(buf);
        let seq = read_2bit_record(&mut cursor, false, None, None, false)?;
        assert_eq!(seq, dna);
        Ok(())
    }

    #[test]
    fn test_record_roundtrip_with_mask() -> Result<()> {
        let dna = "aaGTcc"; // lowercase = soft mask
        let mut buf = Vec::new();
        write_2bit_record(&mut buf, dna, true)?;

        let mut cursor = Cursor::new(buf.clone());
        // with mask applied
        let seq = read_2bit_record(&mut cursor, false, None, None, false)?;
        assert_eq!(seq, dna);

        let mut cursor = Cursor::new(buf);
        // no mask -> uppercase
        let seq_no_mask = read_2bit_record(&mut cursor, false, None, None, true)?;
        assert_eq!(seq_no_mask, "AAGTCC");
        Ok(())
    }

    #[test]
    fn test_record_roundtrip_with_n() -> Result<()> {
        let dna = "ACGTNNNNTTTT";
        let mut buf = Vec::new();
        write_2bit_record(&mut buf, dna, false)?;

        let mut cursor = Cursor::new(buf);
        let seq = read_2bit_record(&mut cursor, false, None, None, false)?;
        assert_eq!(seq, dna);
        Ok(())
    }

    #[test]
    fn test_record_slice() -> Result<()> {
        let dna = "ACGTACGTACGT";
        let mut buf = Vec::new();
        write_2bit_record(&mut buf, dna, false)?;

        let mut cursor = Cursor::new(buf);
        let seq = read_2bit_record(&mut cursor, false, Some(2), Some(8), false)?;
        assert_eq!(seq, &dna[2..8]);
        Ok(())
    }

    #[test]
    fn test_record_empty_slice() -> Result<()> {
        let dna = "ACGT";
        let mut buf = Vec::new();
        write_2bit_record(&mut buf, dna, false)?;

        let mut cursor = Cursor::new(buf);
        let seq = read_2bit_record(&mut cursor, false, Some(2), Some(2), false)?;
        assert_eq!(seq, "");
        Ok(())
    }

    #[test]
    fn test_record_non_acgt_becomes_n() -> Result<()> {
        // U/R and IUPAC ambiguity codes are not valid DNA bases; they should be
        // stored as N-blocks rather than silently packed as T.
        let dna = "ACGTURacgtur";
        let mut buf = Vec::new();
        write_2bit_record(&mut buf, dna, true)?;

        let mut cursor = Cursor::new(buf.clone());
        let seq = read_2bit_record(&mut cursor, false, None, None, false)?;
        assert_eq!(seq, "ACGTNNacgtnn");

        let mut cursor = Cursor::new(buf);
        let seq_no_mask = read_2bit_record(&mut cursor, false, None, None, true)?;
        assert_eq!(seq_no_mask, "ACGTNNACGTNN");

        Ok(())
    }

    #[test]
    fn test_u32_dna_size_rejects_overflow() {
        assert!(u32_dna_size((u32::MAX as usize) + 1).is_err());
        assert_eq!(u32_dna_size(4).unwrap(), 4);
        assert_eq!(u32_dna_size(u32::MAX as usize).unwrap(), u32::MAX);
    }
}
